# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x05infos\"\x94\x02\n\x06Person\x12\x0b\n\x03\x61ge\x18\x02 \x02(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\"\n\x05score\x18\x04 \x03(\x0b\x32\x13.infos.Person.Score\x12)\n\x06number\x18\x05 \x01(\x0b\x32\x19.infos.Person.PhoneNumber\x1a&\n\x05Score\x12\x0e\n\x06object\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x1aK\n\x0bPhoneNumber\x12\r\n\x05phone\x18\x01 \x02(\x05\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x17.infos.Person.PhoneType:\x06MOBILE\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04WORK\x10\x01\x12\x08\n\x04HOME\x10\x02\"0\n\x03one\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x1d\n\x06people\x18\x02 \x02(\x0b\x32\r.infos.Person')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSON_SCORE = _PERSON.nested_types_by_name['Score']
_PERSON_PHONENUMBER = _PERSON.nested_types_by_name['PhoneNumber']
_ONE = DESCRIPTOR.message_types_by_name['one']
_PERSON_PHONETYPE = _PERSON.enum_types_by_name['PhoneType']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'Score' : _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_SCORE,
    '__module__' : 'person_pb2'
    # @@protoc_insertion_point(class_scope:infos.Person.Score)
    })
  ,

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_PHONENUMBER,
    '__module__' : 'person_pb2'
    # @@protoc_insertion_point(class_scope:infos.Person.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:infos.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Score)
_sym_db.RegisterMessage(Person.PhoneNumber)

one = _reflection.GeneratedProtocolMessageType('one', (_message.Message,), {
  'DESCRIPTOR' : _ONE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:infos.one)
  })
_sym_db.RegisterMessage(one)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=24
  _PERSON._serialized_end=300
  _PERSON_SCORE._serialized_start=140
  _PERSON_SCORE._serialized_end=178
  _PERSON_PHONENUMBER._serialized_start=180
  _PERSON_PHONENUMBER._serialized_end=255
  _PERSON_PHONETYPE._serialized_start=257
  _PERSON_PHONETYPE._serialized_end=300
  _ONE._serialized_start=302
  _ONE._serialized_end=350
# @@protoc_insertion_point(module_scope)
